delete_access_iam_roles:
- a204383-PowerUser2
dryrun_enabled: true
environment_type: PRODUCTION
iam_role: arn:aws:iam::012345678987:role/service-role/a000000-project-code-deploy
notification_emails:
- farid.delgado@thomsonreuters.com
stage_order:
- infra
