delete_access_iam_roles:
- a204383-PowerUser2
dryrun_enabled: true
environment_type: DEVELOPMENT
iam_role: arn:aws:iam::962390577453:role/service-role/a204383-service-cloud-iac-lab-farid-delgado-deploy
notification_emails:
- farid.delgado@thomsonreuters.com
stage_order:
- infra
